import { z } from 'zod'

const configSchema = z.object({
  NEXT_PUBLIC_API_ENDPOINT: z.string(),
  NEXT_PUBLIC_URL: z.string(),
  NEXT_PUBLIC_PAGE_SIZE:z.string(),
  NEXT_PUBLIC_PAGE_SIZE_MAIN:z.string(),
  NEXT_PUBLIC_PAGE_SIZE_REF:z.string(),
  NEXT_PUBLIC_GOOGLE_CLIENT_SECRET:z.string(),
  NEXT_PUBLIC_GOOGLE_CLIENT_ID:z.string(),
  NEXT_PUBLIC_PARTNER_ID_CHANGE:z.string(),
  NEXT_PUBLIC_PARTNER_KEY_CHANGE:z.string(),
  NEXT_PUBLIC_WEB2M_ATM_URL:z.string(),
  NEXT_PUBLIC_WEB2M_ATM_PASSWORD:z.string(),
  NEXT_PUBLIC_WEB2M_ATM_ACCOUNT_NUMBER:z.string(),
  NEXT_PUBLIC_WEB2M_ATM_TOKEN:z.string(),
  NEXT_PUBLIC_WEB2M_MOMO_TOKEN:z.string(),
  NEXT_PUBLIC_WEB2M_MOMO_URL:z.string()
})

const configProject = configSchema.safeParse({
  NEXT_PUBLIC_API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT,
  NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
  NEXT_PUBLIC_PAGE_SIZE:process.env.NEXT_PUBLIC_PAGE_SIZE,
  NEXT_PUBLIC_PAGE_SIZE_REF:process.env.NEXT_PUBLIC_PAGE_SIZE_REF,
  NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET,
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  NEXT_PUBLIC_PARTNER_ID_CHANGE: process.env.NEXT_PUBLIC_PARTNER_ID_CHANGE,
  NEXT_PUBLIC_PARTNER_KEY_CHANGE: process.env.NEXT_PUBLIC_PARTNER_KEY_CHANGE,
  NEXT_PUBLIC_WEB2M_ATM_URL:process.env.NEXT_PUBLIC_WEB2M_ATM_URL,
  NEXT_PUBLIC_WEB2M_ATM_PASSWORD:process.env.NEXT_PUBLIC_WEB2M_ATM_PASSWORD,
  NEXT_PUBLIC_WEB2M_ATM_ACCOUNT_NUMBER:process.env.NEXT_PUBLIC_WEB2M_ATM_ACCOUNT_NUMBER,
  NEXT_PUBLIC_WEB2M_ATM_TOKEN:process.env.NEXT_PUBLIC_WEB2M_ATM_TOKEN,
  NEXT_PUBLIC_WEB2M_MOMO_TOKEN:process.env.NEXT_PUBLIC_WEB2M_MOMO_TOKEN,
  NEXT_PUBLIC_WEB2M_MOMO_URL:process.env.NEXT_PUBLIC_WEB2M_MOMO_URL,
  NEXT_PUBLIC_PAGE_SIZE_MAIN:process.env.NEXT_PUBLIC_PAGE_SIZE_MAIN
})

if (!configProject.success) {
  console.error(configProject.error.issues)
  throw new Error('Các giá trị khai báo trong file .env không hợp lệ')
}

const envConfig = configProject.data
export default envConfig