import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";
import ContextProvider from "@/AppProvider/ContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-customFont">
      <ContextProvider>
        <Header></Header>
          <div className="pt-[140px]">
            {children}
          </div>
          <Footer></Footer>
      </ContextProvider>
      </body>
    </html>
  );
}
